### PR TITLE
Fix responsive behavior for show page record toolbar

### LINKED ISSUE #1494: sul-toolbar floats left in mobile view
`.sul-toolbar` is left-aligned in show views `sm` and lower. The navbar collapse button is missing from article show view.

## Example

sul-toolbar-bug

### PR DESCRIPTION
**Pull request by camillevilla**
Closes #1494

This PR
- fixes responsive behavior for the show page record toolbar
- moves record toolbar to a shared partial
- fixes search target dropdown alignment

## Before
sul-toolbar-bug

### Article
article-record-toolbar

### Catalog
catalog-record-toolbar

### CODE REVIEW

File: spec/features/blacklight_customizations/record_toolbar_spec.rb [hunk 1]
```diff
@@ -13,7 +13,7 @@
 
       within "div.navbar-header" do
         expect(page).to_not have_css("button.navbar-toggle", visible: true)
-        expect(page).to_not have_css("a.btn.btn-sul-toolbar", text:"Back to results", visible: true)
+        expect(page).to have_css("a.btn.btn-sul-toolbar", text:"Back to results", visible: true)
```
Comment (camillevilla) [inline spec/features/blacklight_customizations/record_toolbar_spec.rb]: I'm not exactly sure what this scenario (`/spec/features/blacklight_customizations/record_toolbar_spec.rb:9`) is actually testing. This behavior doesn't seem to work in the app right now (see demo), but it's also not failing this particular test.

toolbar-hide

**Comment by camillevilla** [comment]
@jvine can I get a design review for this? Let me know if hopping on Screenhero would be helpful.

**Comment by jvine** [comment]
@camille, a few things -

1) the catalog/article pulldown is sometimes pushed left so it doesn't align with its underline and overlaps the SW logo
screen shot 2017-08-10 at 11 01 49 am

2) the black-on-brown hover state for the sub-menu doesn't work for accessibility. Given some upcoming changes, best bet would be adding text-decoration: underline in the hover/focus state.
screen shot 2017-08-10 at 11 01 23 am

3) Library services is now separated from the collapsed menu and on a row by itself
screen shot 2017-08-10 at 11 01 43 am

If there's something specific you wanted feedback on that I've missed, let me know and we can screenhero.

**Comment by camillevilla** [comment]
@jvine I've addressed (1) and (2) and updated the demo GIFs. (3) was an error on my part; I had the menu open when I was recording.

**Comment by camillevilla** [comment]
alrighty @jkeck, this one's ready for review.
