### PR TITLE
Force library hours display to Pacific time

### LINKED ISSUE #3940: Library hours inaccurate on record detail view
**Environment:** Production

**Steps to reproduce:**

1. Go to any of the following record views:
-- https://searchworks.stanford.edu/view/in00000039980 (Green Library)
-- https://searchworks.stanford.edu/view/3305821 (Law Library)
-- https://searchworks.stanford.edu/view/L354432 (Lane Medical Library)
-- https://searchworks.stanford.edu/view/in00000011584 (Business Library)
2. Scroll to At the library
3. Note the library and hours listed
4. Click on the library link (above the hours)
5. Note the library hours on the library website and/or "branch" page on the SUL website

**Expected result:** Library hours **are the same in SearchWorks** as the library's hours listed on their respective websites/pages. It should be verified that the website hours are correct for each of these.

**Actual result:** Library hours **are different in SearchWorks** from the library's hours listed on their respective websites/pages. 

**Screenshots/visuals:**

From the Business Library example - link listed above: 
Image
Image

### PR DESCRIPTION
**Pull request by taylor-steve**
Addresses the time zone issue in #3940.

### CODE REVIEW

File: app/javascript/location-hours.js [hunk 1]
```diff
@@ -66,14 +66,28 @@ Blacklight.onLoad(function(){
...
+      const formatter = new Intl.DateTimeFormat('en-US', {
+        timeZone: 'America/Los_Angeles',
+        year: 'numeric',
+        month: '2-digit',
+        day: '2-digit',
+        hour: '2-digit',
+        minute: '2-digit',
+        second: '2-digit'
+      });
+      return new Date(formatter.format(date));
```
Comment (jcoyne) [inline app/javascript/location-hours.js:80]: Can we just return the string here?  If you do `new Intl.DateTimeFormat('en', {timeZone: 'America/Los_Angeles', timeStyle: 'short'}).format(date)` then you can simply trim the `:00` and translate the meridian from `AM` to `a`

Comment (taylor-steve) [reply app/javascript/location-hours.js]: Yes, you are right, no need to jump through extra hoops here.
