### PR TITLE
Only show the bound-with message in the appropriate library

### LINKED ISSUE #4049: Only show bound-with notice on locations that have a bound-with holding
I think we're going to revisit this as part of our upcoming work on bound-with. However, it looks like our check for bound-with items on the index view isn't appropriately scoped to the location so we incorrectly repeat the bound-with notice for each location:

Example record: https://searchworks.stanford.edu/?search_field=search&q=id%3A5684521

We should only be showing the bound-with notice/link for the SAL3 location and not Spec.
Screenshot 2024-02-28 at 9 36 30 AM

I think the fix is going to be to change the [SearchResult::LocationComponent#bound_with?](https://github.com/sul-dlss/SearchWorks/blob/02bccb8ea5bedf91eb4454ed957d7c60ea34689c/app/components/search_result/location_component.rb#L20) method to check only for bound-withs within the location and not all the items in the document.

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #4049

### CODE REVIEW

File: spec/components/search_result/location_component_spec.rb [hunk 1]
```diff
@@ -101,4 +101,61 @@
...
+              ]
+            }
+          ]
+        )
+      end
+
+      context 'when looking at SAL3' do
+        let(:library) { document.holdings.libraries.first }
+
+        it "doesn't show" do
```
Comment (corylown) [inline spec/components/search_result/location_component_spec.rb:147]:
```suggestion
        it "does show" do
```

**Review by corylown — CHANGES_REQUESTED** [review]
Confirmed that it fixes #4049. One suggested change for a test description.

File: spec/components/search_result/location_component_spec.rb (hunk 1 above)
Comment (jcoyne) [reply spec/components/search_result/location_component_spec.rb]: Good eye! I've fixed this.

**Review by corylown — APPROVED** [review]
