### PR TITLE
fix due date when using back button

### LINKED ISSUE #4204: Due dates duplicating for boundwith records after using the browser "back" button
We got a report via SearchWorks feedback (from a library staff member) that praised when we show the due date from the parent record on the child record in "At the library". But the feedback was qualified that the due date "displays twice".  It appears that the due date is duplicated each time the browser back button is used. This seems to happen on both the parent on the child record. But it's particular obvious when you click on a child record, then the link to the parent record.  The only way to get back to the child record is to use the browser back button.

Here's a screen shot after using the back button twice on a child record:
image

Boundwith record used in the report: 
https://searchworks.stanford.edu/view/8003016

### PR DESCRIPTION
**Pull request by dnoneill**
closes #4204

### CODE REVIEW

File: app/javascript/controllers/live_lookup_controller.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ export default class extends Controller {
           status_text.html(live_data.status)
         }
 
-        if (live_data.due_date) {
+        if (live_data.due_date && !temporary_location.text().includes('Due')) {
```
Comment (jcoyne) [inline app/javascript/controllers/live_lookup_controller.js:28]: Would you mind adding a code comment here explaining what this is doing?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/javascript/controllers/live_lookup_controller.js [hunk 2]
```diff
@@ -25,7 +25,8 @@ export default class extends Controller {
           status_text.html(live_data.status)
         }
 
-        if (live_data.due_date) {
+        // Check if there is a due date and if the due date is already in temporary location.
```
Comment (jcoyne) [inline app/javascript/controllers/live_lookup_controller.js:28]: Why would there already be a due date?  Can you give a bit more context?

**Review by jcoyne — CHANGES_REQUESTED** [review]

**Review by jcoyne — APPROVED** [review]
