### PR TITLE
persist the EDS session token between Blacklight sessions

### LINKED ISSUE #1412: Persist the EDS session token between searches
The EDS API will fail when asking for the 251st result on a new session. We're currently issuing all searches as a new-session. Persisting the session token should improve performance too.

### PR DESCRIPTION
**Pull request by drh-stanford**
This PR fixes #1412.

Verified that it's working correctly with Bill and Eric on Slack. Basically you can look at the Faraday logs to see the API traffic (set EDS_DEBUG=true in your setteings). It should not issue a CreateSession call unless you clear your browser cookies.

### CODE REVIEW

File: app/controllers/article_controller.rb [hunk 1]
```diff
@@ -91,4 +83,18 @@ def search_service
   def set_search_query_modifier
     @search_modifier ||= SearchQueryModifier.new(params, blacklight_config)
   end
+
+  # Reuse the EDS session token if available in the user's session data,
+  # otherwise establish a session
+  def setup_eds_session(session)
+    return if session['eds_session_token'].present?
+    session['eds_session_token'] = EBSCO::EDS::Session.new(
+      guest: session['guest'],
```
Comment (jkeck) [inline app/controllers/article_controller.rb]: Hmm, this has me thinking a bit.  The only time that the `guest` status is going to change is when the user logs in or out.  At log-in time, we'll need to determine if the user should be in guest mode or not.  I guess I'm just a bit worried about storing the `guest` status in the session w/o a good handle on how that session variable might get set/unset.

What would you think about just hard-coding this to be `true`, removing the `guest` session variable, and hammering out the implementation details when we need to implement non-guest sessions?

Comment (cbeer) [inline app/controllers/article_controller.rb]: There's also some callback in `devise-guests` when a guest user logs in you might use to update the session. `logging_in_user`, maybe?

Comment (drh-stanford) [inline app/controllers/article_controller.rb]: This should be addressed in 69d2357.
