### PR TITLE
fix browser back duplicate results, closes #3643

### LINKED ISSUE #3643: Zero-results number is duplicated on browser back
We think this may be a turbolinks issue

Steps to reproduce:
1. navigate to a zero results page such as https://searchworks-stage.stanford.edu/?f%5Baccess_facet%5D%5B%5D=On+order&search_field=call_number&q=%22amber%22
2. Click one of the Remove limits links to navigate away from this page
3. Hit your browser's back button to return to the zero results page

Result:
Screen Shot 2023-10-18 at 2 07 20 PM

### PR DESCRIPTION
**Pull request by dnoneill**

### CODE REVIEW

File: app/javascript/backend_lookup.js [hunk 1]
```diff
@@ -30,8 +30,10 @@ Blacklight.onLoad(function(){
     }
 
     function updateText(count, el){
-      countText = $("<span>...finds " + count + " results</span>");
-      $(el).after(countText);
+      if (!$(el)[0].nextElementSibling){
```
Comment (jcoyne) [inline app/javascript/backend_lookup.js:33]: Would you mind adding a comment here explaining what this is doing?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/javascript/backend_lookup.js (hunk 1 above)
Comment (dnoneill) [reply app/javascript/backend_lookup.js:34]: Done.

**Review by jcoyne — APPROVED** [review]
