### PR TITLE
Set the qurl rather than url param for ezproxy links

### LINKED ISSUE #3064: 856 field URLs that have a proxy-prefix added by SearchWorks are not working
This is somewhat confusing because some records still have a proxy-prefix added before the record is indexed (these work) and others get their proxy prefix by SearchWorks (these don't work). I'll give examples of both.

Acquisitions reports that the link on this record [14443980](https://searchworks.stanford.edu/view/14443980) goes to the ezproxy list rather than the resource. This record has the proxy prefix added by SearchWorks and the `url` parameter value is getting URI encoded, like this:
```
https://stanford.idm.oclc.org/login?url=https%3A%2F%2Fsearch.ebscohost.com%2Flogin.aspx%3Fauthtype%3Dip%2Csso%26custid%3Ds4392798%26direct%3Dtrue%26scope%3Dsite%26db%3Dnlebk%26db%3Dnlabk%26AN%3D743247
```

If I decode the parameter value the link works:
```
https://stanford.idm.oclc.org/login?url=https://search.ebscohost.com/login.aspx?authtype=ip,sso&custid=s4392798&direct=true&scope=site&db=nlebk&db=nlabk&AN=743247
```

On records like [8785205](https://searchworks.stanford.edu/view/8785205) where the proxy prefix is getting added before indexing the url parameter values are unencoded and the links work:

```
https://stanford.idm.oclc.org/login?url=https://search.proquest.com/pqrl?accountid=14026
```

### PR DESCRIPTION
**Pull request by marlo-longley**
Closes #3064

### CODE REVIEW

File: lib/search_works/links.rb [hunk 1]
```diff
@@ -28,7 +28,9 @@ def self.ezproxy_url(url, document)
                        Settings.EZPROXY.SUL
                      end
 
-      "#{ezproxy_host}#{{ url: url }.to_param}" if ezproxy_host
+      # set the 'qurl' param rather than 'url'
```
Comment (corylown) [inline lib/search_works/links.rb:31]:
```suggestion
      # EZproxy requires the use of the `qurl` param instead of `url` when the value is an encoded URL.
```

**Comment by marlo-longley** [comment]
For Lane and Law, tested the following URLs successfully:

https://login.laneproxy.stanford.edu/login?qurl=https%3A%2F%2Fbooks.google.com%2Fbooks%3Fvid%3DStanford24504135193%26printsec%3Dtitlepage

https://ezproxy.law.stanford.edu/login?qurl=https%3A%2F%2Fapp.investorstatelawguide.com%2FDashboard

**Review by corylown — APPROVED** [review]
